modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "animal_pen"
version = "${version}"
displayName = "Animal Pen"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.animal_pen]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"
