modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "animal_pen"
version = "${version}"
displayName = "Animal Pen"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.animal_pen]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "architectury"
mandatory = true
versionRange = "[5.14.84,)"
ordering = "AFTER"
side = "BOTH"
