modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "animal_pen"
version = "${version}"
displayName = "Animal Pen"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.animal_pen]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
