modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/BONNePlayground/AnimalPen/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "animal_pen"
version = "${version}"
displayName = "Animal Pen"
authors = "BONNe1704"
description = '''
A simple mod aimed to reduce lag on servers by placing animals in single block.
'''
logoFile = "assets/animal_pen/icon.png"

[[dependencies.animal_pen]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "architectury"
mandatory = true
versionRange = "[8.2.91,)"
ordering = "AFTER"
side = "BOTH"
