# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
version=2.4.1
group=lv.id.bonne
java_version=25
archives_name = animal_pen
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version=26.1
pack_version=101
mod_name=Animal Pen
mod_author=BONNe
mod_id=animal_pen
mod_license=GNU GPL 3.0
mod_credits=
mod_description=A simple mod aimed to reduce lag on servers by placing animals in single block.
minecraft_version_range=[26.1, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1
# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.5
# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.0.8-beta
neoforge_loader_version_range=[4,)

# https://www.curseforge.com/minecraft/mc-mods/cloth-config for new versions
cloth_config_version=26.1.154
# https://www.curseforge.com/minecraft/mc-mods/modmenu/ for new versions
modmenu_version=18.0.0-alpha.8
# https://www.curseforge.com/minecraft/mc-mods/text-placeholder-api/ for new versions
placeholder_api_version=3.0.0+26.1
# https://www.curseforge.com/minecraft/mc-mods/jei for new versions
jei_version=29.2.0.21

observable_version=6401030