//
// Created by BONNe
// Copyright - 2026
//

package lv.id.bonne.animalpen.interaction.loot;


import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;

import org.jetbrains.annotations.NotNull;
import java.util.ArrayList;
import java.util.List;

import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.storage.loot.LootParams;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSets;
import net.minecraft.world.level.storage.loot.parameters.LootContextParams;
import net.minecraft.world.phys.Vec3;


/**
 * This record stores how loot should be processed for interaction
 * @param lootTable - the loot table of interaction
 * @param dropLimit - the maximal drop limit of item
 * @param perEntity - the indication if loot is rolled once or per each entity
 */
public record LootEntry(ResourceLocation lootTable, int dropLimit, boolean perEntity)
{
    /**
     * This method creates list of items generated by loot-table in interaction.
     *
     * @param serverLevel The level where interaction happens
     * @param animal The animal that are interacted with
     * @param blockPos The position of interacted block
     * @param animalCount The amount of animals interacted
     * @return List of item stacks that are generated by loot table.
     */
    @NotNull
    public List<ItemStack> processLootTable(ServerLevel serverLevel,
        Mob animal,
        BlockPos blockPos,
        int animalCount)
    {
        int itemCount = this.dropLimit();

        LootTable lootTable = serverLevel.getServer().getLootData().getLootTable(this.lootTable());

        LootParams params = new LootParams.Builder(serverLevel).
            withParameter(LootContextParams.THIS_ENTITY, animal).
            withParameter(LootContextParams.ORIGIN, Vec3.atCenterOf(blockPos)).
            create(LootContextParamSets.GIFT);

        List<ItemStack> itemStackList = new ArrayList<>();
        int rollCount = this.perEntity() ? animalCount : 1;

        while (itemCount > 0 && rollCount-- > 0)
        {
            List<ItemStack> randomItems = lootTable.getRandomItems(params);

            if (randomItems.isEmpty())
            {
                // Just a stop on infinite loop
                break;
            }

            itemCount -= randomItems.stream().mapToInt(ItemStack::getCount).sum();

            randomItems.forEach(item ->
            {
                boolean added = false;

                for (ItemStack stack : itemStackList)
                {
                    if (ItemStack.isSameItemSameTags(item, stack) &&
                        stack.getCount() + item.getCount() <= stack.getMaxStackSize())
                    {
                        stack.grow(item.getCount());
                        added = true;
                        break;
                    }
                }

                if (!added)
                {
                    itemStackList.add(item);
                }
            });
        }

        return itemStackList;
    }


    public static LootEntry of(ResourceLocation resourceLocation, int dropLimit, boolean perEntity)
    {
        return new LootEntry(resourceLocation, dropLimit, perEntity);
    }


    public static LootEntry of(ResourceLocation resourceLocation)
    {
        return new LootEntry(resourceLocation, Integer.MAX_VALUE, false);
    }


    public static final Codec<LootEntry> CODEC =
        RecordCodecBuilder.create(instance -> instance.group(
            ResourceLocation.CODEC.fieldOf("id").forGetter(LootEntry::lootTable),
            Codec.INT.fieldOf("drop_limit").forGetter(LootEntry::dropLimit),
            Codec.BOOL.fieldOf("per_entity").forGetter(LootEntry::perEntity)
        ).apply(instance, LootEntry::new));
}
