modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/BONNePlayground/AnimalPen/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "animal_pen"
version = "${version}"
displayName = "Animal Pen"
authors = "BONNe1704"
description = '''
A simple mod aimed to reduce lag on servers by placing animals in single block.
'''
logoFile = "assets/animal_pen/icon.png"

[[dependencies.animal_pen]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_pen]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "animal_pen.mixins.json"

[[mixins]]
config = "animal_pen-neoforge.mixins.json"